# Generated by Django 4.1.4 on 2022-12-31 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Common",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_Name", models.CharField(max_length=50)),
                ("DateOfBirth", models.DateField(default="2022-11-21")),
                ("DateOfJoining", models.DateField(default="2022-11-21")),
                ("Address", models.CharField(max_length=100)),
            ],
            options={"db_table": "common",},
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(default="", max_length=50)),
                ("IsActive", models.BooleanField(default=False)),
            ],
            options={"db_table": "master",},
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Compensation", models.CharField(max_length=10)),
                (
                    "Common",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manageApp.common",
                    ),
                ),
            ],
            options={"db_table": "teacher",},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Roll_Number", models.CharField(max_length=20)),
                (
                    "Common",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manageApp.common",
                    ),
                ),
            ],
            options={"db_table": "student",},
        ),
        migrations.AddField(
            model_name="common",
            name="Master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="manageApp.master"
            ),
        ),
    ]
