# Generated by Django 4.1.4 on 2022-12-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Role_Type",
                    models.CharField(
                        choices=[("T", "Teacher"), ("S", "Student")],
                        default="",
                        max_length=5,
                    ),
                ),
            ],
            options={"db_table": "role",},
        ),
    ]
