# Generated by Django 4.1.4 on 2023-01-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageApp", "0002_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="Role_Type",
            field=models.CharField(default="", max_length=8),
        ),
    ]
