# Generated by Django 4.1.4 on 2023-01-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageApp", "0003_alter_role_role_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Club_Name", models.CharField(max_length=50)),
                ("Open_Time", models.CharField(default="10:00 AM", max_length=50)),
                ("Close_Time", models.CharField(default="04:00 PM", max_length=50)),
                ("Head_Of_Club", models.CharField(default="", max_length=50)),
            ],
            options={"db_table": "Club",},
        ),
        migrations.AlterField(
            model_name="role",
            name="Role_Type",
            field=models.CharField(
                blank=True,
                choices=[("T", "Teacher"), ("S", "Student")],
                default="",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="Roll_Number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
