# Generated by Django 4.1.4 on 2023-01-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageApp", "0004_club_alter_role_role_type_alter_student_roll_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="Contact",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterModelTable(name="club", table="club",),
    ]
