# Generated by Django 4.1.4 on 2023-01-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageApp", "0006_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Roll_Number",
            field=models.CharField(max_length=20),
        ),
    ]
